// <auto-generated />
using Chess_Game.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess_Game.Infrastructure.Migrations
{
    [DbContext(typeof(Chess_GameDbContext))]
    [Migration("20240731145631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chess_Game.Domain.Entities.Game", b =>
                {
                    b.Property<int>("id_Game")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Game"));

                    b.Property<int>("TurnsG")
                        .HasColumnType("int");

                    b.Property<string>("opening_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("the_black_rating")
                        .HasColumnType("int");

                    b.Property<int>("the_white_rating")
                        .HasColumnType("int");

                    b.Property<string>("victory_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("winner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Game");

                    b.ToTable("mychess_games");
                });
#pragma warning restore 612, 618
        }
    }
}
